version: 0.2
   
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - ruby -v
      - gem env
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist jekyll-feed
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://www.scottnasello.org
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "E1M7H4NXNTK35Y" --paths "/*"
